# Overrides för enhetstester och komponenttester
quarkus:
  http:
    cors:
      origins: /.*/
  datasource:
    jdbc:
      url: "jdbc:sqlite::memory:"

gredor:
  auth:
    limit:
      per-interval: 10
      per-interval-and-person: 3
      interval-in-hours: 168
  bankid:
    # Används ej i dessa tester
    test-mode: true
  bolagsverket:
    # Används ej i dessa tester
    hamta-arsredovisningsinformation:
      baseurl: unused
    lamna-in-arsredovisning:
      baseurl: unused
  rest:
    v1:
      use-x-real-ip: true
  secrets:
    # Används ej i dessa tester
    cert-bankid:
      path: unused
      password: unused
    cert-bolagsverket:
      path: unused
      password: unused
